version: '3.8'

services:
  drone_ros:
    build:
      context: ./drone_ros_ws
      dockerfile: Dockerfile
    container_name: ros2_humble_dev
    tty: true
    stdin_open: true
    ports:
      # Esponiamo la porta 8080 per accedere all'interfaccia grafica tramite Browser
      - "8080:8080"
    volumes:
      - ./drone_ros_ws/src:/ros2_ws/src
    network_mode: "bridge"

  # Puoi già predisporre gli altri servizi per farli comunicare nella stessa rete
  # cognitive_agent:
  #   build:
  #     context: ./cognitive_agent
  #     dockerfile: Dockerfile
  #   container_name: cognitive_agent_brain
  #   ...